# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  PUBLISHPASS: $(PUBLISHKEY)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: mySecureFile
    inputs:
      secureFile: ""
      retryCount: "2"

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: ""
      sshPublicKey: ""
      sshPassphrase: "$(PUBLISHPASS)"
      sshKeySecureFile: ""

  - script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --local user.email "<mrigankasaha2@gmail.com>"
      git config --local user.name "Mrigankasaha2"
      npm install --no-audit --progress=false      
      npm run deploy
    displayName: "npm install and deploy"
